name: Run unit tests

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'

jobs:
 run-unit-tests:
   runs-on: ubuntu-latest
   container:
     image: docker.io/dataloopai/py3.8.node16:1.74.14
   steps:
     - name: Install dependencies
       run: |
         pip3 install dtlpy --upgrade
     - name: Run tests
       env:
         PROJECT_ID: "${{ secrets.PROJECT_ID }}"
         BOT_EMAIL: "${{ secrets.BOT_EMAIL }}"
         BOT_PWD: "${{ secrets.BOT_PWD }}"
       run: |
         cd tests
         python3 -m unittest tests
